export enum Errors {
  EMPTY_EMAIL = 'Please enter a valid email address',
  EMPTY_USERNAME = 'Please enter your email or mobile number',
  EMPTY_PASSWORD = 'Please enter your password',
  REQUIRED = 'This is a required field',
  INVALID_EMAIL = 'Invalid email format',
  INVALID_MOBILE = 'Please enter a valid mobile number',
  PASSWORD_MISMATCH = 'New password and confirm password did not match',
  INVALID_FIRST_NAME = 'Please use only letters for the First Name field',
  INVALID_LAST_NAME = 'Please use only letters for the Last Name field',
  INVALID_PASSWORD = 'Password must have 8 to 12 characters',
  INVALID_CONFIRM_PASSWORD = 'This is a required field',
  INVALID_BIRTHDAY = 'Birthday is required',
  QUANTITY_EXCEED = 'Quantity cannot exceed available stock',
  INVALID_CREDENTIALS = 'Your credentials are wrong. Please try again.',
  INVALID_FILE_SIZE = 'File must be up to 5mb only',
  INVALID_FILE_FORMAT = 'Invalid file format',
  INVALID_FILE_UPLOAD = 'Upload failed please try again',
  INVALID_MOBILE_INPUT = 'Please use only numbers for the Mobile number field',
  INVALID_ZIPCODE = 'Please use only numbers for the Zip code field',
  INVALID_NAME = "Please use only letters for the Recipient's Name field",
  MAX_ZIPCODE = 'Maximum of 4 numbers only',
  MAX_CHARACTER_ERROR = 'Maximum of 50 characters only',
}
